### ISSUE TITLE
Prefetch addon with Apollo

### ISSUE THREAD

**Issue by loganpowell** [pshrmn/curi#15]
Hi @pshrmn! Just about to get started with Curi and really want to use the prefetch functionality with Apollo's inMemoryCache.  

Here's what I'm trying to do (with reference to: https://github.com/apollographql/react-apollo/issues/417#issuecomment-359261698):

Might you have some guidance for using Curi's prefetch addon with Apollo's inMemoryCache? I'm particularly interested in 'lazy' prefetching/loading, i.e., only prefetch the part of the state needed to render the linked pages/component(s) - with an async data request - when a user navigates to a page/component with relative or child routes/components. I plan on using Apollo for everything (e.g., sans Redux).

Would you recommend using Curi's prefetch or something like [react-preloaded](https://github.com/fubhy/react-preload) for these use cases? I'm such a newb. I'm sorry if this is a dumb question.

**Comment by pshrmn** [comment]
Just so we're on the same page, I'm going to describe some behavior.

The built-in behavior (via the match API) is that you click a link and if the route that matches the new location has `match.initial` or `match.every` functions, those will be called and the response won't be emitted until they are resolved. In a sense, that is prefetching because the application won't re-render until those have finished (as opposed to re-rendering immediately and having a bunch of spinners).

```js
{
  name: 'Album',
  path: 'album/:albumID',
  match: {
    // this will be called the first time the user navigates to an Album page
    initial() {
      return import(/* webpackChunkName: 'album' */ './components/Album.js');
    }
    // this will be called every time the user navigates to an Album page
    every({ params }) {
      return api.getAlbum(params.albumID);
    }
  }
}
```

The `prefetch` addon calls a route's `match.every` function outside of the router's route matching, which allows you to cache the result so that when the user _does_ click that link, you already have the data. (There isn't an analog for `match.initial`, although it would be pretty easy to write one.) This means that you could start loading data when the user hovers their mouse near the link. There isn't a built-in implementation, but something like this would work:

```js
import { Curious, Link } from '@curi/react';

// use <Curious> to access the router
const PrefetchLink = ({ to, params, ...rest}) => (
  <Curious render={({ router }) => (
    <Link
      to={to}
      params={params}
      {...rest}
      onMouseEnter={e => {
        // if the API call made by Album's match.every response is cached,
        // the next call to it should essentially be free
        router.addons.prefetch(to, params);
      }}
  )}/>
);

<PrefetchLink to='Album' params={{ albumID: 7 }}>Album 7</PrefetchLink>
```
(I'm not actually sure what the analog for this in React Native would be because I don't think there is a hover concept with RN.)

---

I haven't had the chance yet to really look into interfacing Curi with Apollo (I've been distracted by React Native), so I'm not actually sure whether making `graphql` calls in `match.every` makes sense (I hope it does!).

I was looking at the Apollo documentation on [prefetching data](https://www.apollographql.com/docs/react/recipes/prefetching.html) and using the query from there, I think it would look something like this.

```js
{
  name: 'Album',
  path: 'album/:albumID',
  match: {
    every({ params }) {
      // you would need to have access to your apollo client in your routes
      return client.query({
        query: ALBUM_QUERY,
        variables: { albumID: params.albumID }
      });
    }
  }
}
```

**Comment by loganpowell** [comment]
This helps a bunch! I'll get to it. Thank you, as always, for your patience.

**Comment by pshrmn** [comment]
Of course. The hardest part of developing Curi has been figuring out what works and what does not, so it is nice to have other people who can offer a fresh perspective. Asking questions forces me to look into things that I haven't thought about/overlooked.

**Comment by loganpowell** [comment]
Sorry, just to follow up on your suggestion:

> The prefetch addon calls a route's match.every function outside of the router's route matching, which allows you to cache the result so that when the user does click that link, you already have the data. 

```js
import { Curious, Link } from '@curi/react';

// use <Curious> to access the router
const PrefetchLink = ({ to, params, ...rest}) => (
  <Curious render={({ router }) => (
    <Link
      to={to}
      params={params}
      {...rest}
      onMouseEnter={e => {
        // if the API call made by Album's match.every response is cached,
        // the next call to it should essentially be free
        router.addons.prefetch(to, params);
      }}
  )}/>
);

<PrefetchLink to='Album' params={{ albumID: 7 }}>Album 7</PrefetchLink>
``` 

Could it also use a React lifecycle event like `componentDidMount` or another lifecycle event?

**Comment by pshrmn** [comment]
If I'm understanding your question correctly, then yes, you can prefetch anywhere you have access to the `router`.

If you don't have direct access to the router, you can use the  `<Curious>` component to inject it into a component's props.

```jsx
class SomeComponent extends React.Component {
  componentDidMount() {
    this.router.addons.prefetch('Some Route', { foo: 'bar' });
  }
}

export default props => (
  <Curious render={curiProps => (
    <SomeComponent {...curiProps} {...props} />
  )} />
);
```
(You could also use `context` directly instead of using `<Curious>`, but it is generally recommended that libs provide a component/higher-order component to do this for you since `context` still isn't complete).

**Comment by loganpowell** [comment]
Perfect. Thank you!

**Comment by pshrmn** [comment]
I just noticed that the `@curi/prefetch` documentation is slightly wrong. The second argument should be an object with `params`, `location`, and `name` properties, not just a `params` object. I updated my comments above and I'll get the updated docs pushed soon.

**Comment by loganpowell** [comment]
It also looks like there's a native [`prefetch`](https://www.apollographql.com/docs/react/recipes/prefetching.html) api in Apollo that can handle this. Just putting it here for posterity ;)
