### ISSUE TITLE
Cache improvements

### ISSUE THREAD

**Issue by KaRkY** [pshrmn/curi#18]
Hello,

I would like to request a few things for caching. First I would like to get information if route was push-ed or pop-ed while inside of cache. Why would I like to have that is so I can delete cache entries while navigating. Basically I do not want to show cached data if somebody clicks a link. But if he presses back or forward button it should load cached data.

Next thing is I would like a way to say refresh data in cache.

**Comment by pshrmn** [comment]
Adding the `action` to the `cache.get` call is easy enough and makes sense to do.

Can you expand on what you mean by "refresh data in cache"? If you want to "expire" an entry, your cache should return `null` because [Curi only emits cached responses if it is not `null`](https://github.com/pshrmn/curi/blob/dcd17a8407526d4bb37b0811b3feabd6f4f9e31d/packages/core/src/curi.ts#L146-L151). That would lead to Curi generating a new response (and re-calling the matching route's `match.every` function).

I don't actually use the cache; it was just a "oh, this might be nice" thought that was easy to implement. A part of me has half-considered removing the cache (I obviously won't now that I know people _are_ using it) because I wasn't sure how useful it really was (data can be cached in stores), so if you have any other feedback on the cache, I would appreciate it.

**Comment by KaRkY** [comment]
About refreshing the cache I mean a situation where data is stale an on users request data gets refreshed. But this can be solved with pushing the same route again so it has similar effect as refreshing the page.

About removing the cache yes I agree it only partially fits inside a router implementation. Maybe the API can be changed in a way so it can be implemented as a addon. A cache solution to me fells more like an addon.

Currently I do not use curi yet but I plan to use it.

**Comment by pshrmn** [comment]
> a situation where data is stale an on users request data gets refreshed

This is where I question whether the `cache` is necessary or not. For me, I would rather have my data fetching/store implementation decide whether to re-use existing data or make a new request. Then, while generating a new response, instead of checking the cache, the `match.every` function for the matched route would just resolve with cached data instead of making a network request.

```js
const routes = [
  {
    name: 'Some Route',
    path: 'somewhere/:param',
    match: {
      every({ params }) {
        // ideally, you would write your API to handle caching for you here
        return API.getSomeData(params.param);
      }
    }
  }
]
```

**Comment by loganpowell** [comment]
@KaRkY what are you using for your `store`? Have you considered [Apollo Client](https://www.apollographql.com/docs/react/features/cache-updates.html#refetchQueries). There seems to be some nice overlap with what you're trying to accomplish with the cache there. Perhaps it's a play between Apollo and Curi to get what you want.

**Comment by KaRkY** [comment]
My main idea was to remove any store implementation and think about data in a way that URL defines the data that schould be loaded.

Appolo Client is as far as I know for GraphQL and I will probably be using gRPC-Web when it comes out. 

At the momemnt I am evaluating tech stack I will be using in a future project.
