### ISSUE TITLE
Transitions Example

### ISSUE THREAD

**Issue by loganpowell** [pshrmn/curi#20]
Hi @pshrmn ! I am just about ready to integrate Curi into my app and am working with [a tutorial](https://hackernoon.com/animated-page-transitions-with-react-router-4-reacttransitiongroup-and-animated-1ca17bd97a1a) that uses react router with [`Animated`](https://github.com/animatedjs/animated) and [`ReactTransitionGroup` v2](https://github.com/reactjs/react-transition-group). There's some funky .css that the author uses to prevent the issue that you outlined in [your tutorial](https://medium.com/@pshrmn/a-shallow-dive-into-react-router-v4-animated-transitions-4b73f634992a) in [this sandbox](https://codesandbox.io/s/oxkw5prm56?from-embed) and I was hoping to glean some insights from the example that now I can only find a [dead link on Google's results](https://www.google.com/search?safe=off&rlz=1C1CHFX_enUS685US685&ei=3PZoWryJKoj0zgL9wI6oBA&q=curijs+transitions&oq=curijs+transition&gs_l=psy-ab.1.0.35i39k1.108.544.0.1764.7.4.0.0.0.0.201.539.1j2j1.4.0....0...1.1.64.psy-ab..3.4.535....0.KosqJt8-90k) to.

You might be wondering why I'm choosing `animated`. It could help to clarify that I'd like to build my app in a manner that could be more easily ported to React Native. Hence, all the other inquiries (and lack of knowledge).

**Comment by pshrmn** [comment]
I grouped the examples by framework a month or so ago, which is why that one link is 404ing. You can see it here: https://curi.js.org/examples/react/transitions/. I just noticed that the description for that example is based on `ReactTransitionGroup` v1, so I will need to update that later. Instead, you should take a look at `renderFunction.js` to see how I used the transition group.

I should probably setup some redirects in the docs site, but there isn't a good way to do that with static pages (I just use GH pages to host the docs site, which ends up with a convoluted setup because I have to generate an `index.html` for every valid location, but I wanted "pretty" URLs). Hopefully Google notices that it 404s soon and drops that link.

I haven't read that tutorial yet, but I'll add another comment once I do.

**Comment by loganpowell** [comment]
oh yeah! I didn't even think of that! You should use redirects with Curi for you github pages!

**Comment by loganpowell** [comment]
This is what I'm using for static page gen: https://github.com/stereobooster/react-snap

**Comment by pshrmn** [comment]
Okay, I just had a chance to look at that tutorial and I really don't like that it uses multiple `<TransitionGroup>`s (although that is irrelevant with Curi).

The `AnimatedWrapper` is using the `react-transition-group` v1 API. With v2, I think you would have to use the `<Transition>` component, however I dont't know enough about `Animated` to say how to integrate it with `r-t-g` v2. I'm going to be playing with `Animated` in React Native, so hopefully I'll be able to provide a better answer soon.

**Comment by loganpowell** [comment]
Yep, with v2 the `<Transition>` component is the way to go.
