### ISSUE TITLE
Customizing styles of `useNavigationFocus` / ref

### ISSUE THREAD

**Issue by loganpowell** [pshrmn/curi#228]
Hi Paul! Long time, no talk man.

I'm finally coming around to Curi again and I love all the progress you've made. I'm just re-familiarizing myself with the library again and running through the docs. I already have a question:

Is there a way to prevent the default blue border around the aria focused element when using the `useNavigationFocus` hook? I would like to incorporate this feature for screen readers, but handle the focus styles myself. This could be obvious for anyone with experience with these dom features, but this is a first for me.

Thank you for the great work! 

PS: you should totally steal some of the marketing copy from [`navi'](https://frontarm.com/navi/en/motivation/) for Curi. You have all those features and more.

**Comment by pshrmn** [comment]
That can be controlled using the `outline` CSS property. I explicitly leave it in in the examples so that it is more obvious what element is focused. Some people disable outline (`* { outline: none }`), but that is bad for keyboard users who need visual cues to know what is currently focused.

I think that best approach is to use [`:focus-visible`](https://css-tricks.com/almanac/selectors/f/focus-visible/) so that you can hide the outline for mouse users, but show it for keyboard users. This doesn't actually have full browser support yet, but the [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible) docs have a link to a "polyfill". (I'm not sure if it really counts as a polyfill since you have to use a class instead of the pseudo-selector syntax.)

As far as marketing goes, I have some ideas for making people more aware that Curi exists, but I've been pretty busy with other stuff. Hopefully sometime soon I have time to work on that.

**Comment by loganpowell** [comment]
Thank you for the advice. Looking forward to working with the library!
