### ISSUE TITLE
Nested components and shared structure

### ISSUE THREAD

**Issue by fiftydegrees** [pshrmn/curi#3]
According the the [migration guide](https://curi.js.org/guides/migrate-rrv3/):

> With Curi, when a nested route matches, only that route renders.

**How to tackle the case of a fixed navbar in a parent component with injected components under the navbar?** With React Router, it's possible to handle this by using `this.props.children` in the parent component because nested routes also render parent components.

Thanks for help, that library seems pretty cool, looking forward to using it!

**Comment by pshrmn** [comment]
Would you be able to include some (pseudo) JSX to show what you would do in React Router?

I'm taking a bit of a guess here about what your navbar is supposed to be, but one possibility would be to have your routes' `body` functions return an object instead of a component.

```js
const routes = [
  ...,
  {
    name: 'Parent',
    path: 'parent',
    body: () => ({
      main: Parent,
      nav: [ParentNav]
    }),
    children: [{
      name: 'Child',
      path: ':child',
      body: () => ({
        main: Child,
        nav: [ParentNav, ChildNav]
      })
    }]
  }
];
```
The idea with that is that in your render function, you would pass `response.body.nav` to your navbar and it would render those components.
```js
function render(response) {
  const { body } = response;
  const { nav, main: Main } = body;
  return (
    <div>
      <NavBar components={nav} />
      <Main />
    </div>
  );
}
```
Hopefully that answer is on the right track, but if not, I'd be happy to take a closer look if you can help me better understand what you're trying to do.

**Comment by fiftydegrees** [comment]
@pshrmn Thanks, that's what I was looking for! I just want the navbar to appear on each "view" and display a different child below depending on the current route, this is made possible by passing multiple arguments to the body function. Thanks for the cool library by the way! 👋🏼
