### ISSUE TITLE
[RFC] Programmatically navigate by route name

### ISSUE THREAD

**Issue by huygn** [pshrmn/curi#44]
Would be awesome if we can do `router.history.navigate('About')`. Currently only `router.history.navigate('/about')` works.

**Comment by pshrmn** [comment]
Currently, the way to do this would be to use the `pathname` addon to generate the pathname and then pass that to `history.navigate`.

```js
const pathname = router.addons.pathname('About');
router.history.navigate({ pathname });
```

Passing the route name to `history.navigate` wouldn't work because it isn't actually aware of your routes. The history object is mostly just an interface with the browser.

I have considered adding some shortcut methods directly to the router before that would be the same as your request.

```js
// internally, this would do the same thing as the above snippet
router.navigate({ name: 'About' });
// this uses an object since it would have to work with route params
// as well as query, hash, and state data
```
I am open to adding this if a number of people do want this, but so far I haven't really felt the need because calling the addon and passing it was just one extra call and I didn't want to pile too many things onto the router API.

Let's leave this open for a bit as a request for comment.

**Comment by pshrmn** [comment]
I decided that the convenience of this functionality is worth it. I had merged all of the `history` navigation methods into one earlier, so I only had to add one method to the router. Will release shortly.
