### ISSUE TITLE
Curi + React Native integration

### ISSUE THREAD

**Issue by amorenew** [pshrmn/curi#7]
I wonder if it works on React Native too?

**Comment by pshrmn** [comment]
Yes and no. Most of the `@curi/react` components should work with React Native, but I don't think the `<Link>` would. You can pass it a custom component, so that isn't the issue, but I think that you need to use `onPress` to handle clicks, while the `@curi/react` `<Link>` uses `onClick`. Maybe I'm wrong, but I haven't experimented with that at all. It wouldn't be too hard to add a `@curi/react-native` package, so if that is something people want, I'd be happy to look into it.

The other thing you would need to keep in mind is that you would have to use an in-memory history instead of a browser history.

```bash
npm install @hickory/in-memory
```
```js
import InMemory from '@hickory/in-memory';

const history = InMemory();
const router = curi(history, routes);
```

**Comment by loganpowell** [comment]
Jumping on this closed issue to follow your progress and break the ice for anyone else who stumbles here ;)

**Comment by pshrmn** [comment]
I just opened #11, which adds a React Native package. I'll merge it once I get the tests working and then publish an alpha release. It might be a bit before I get any examples/guides put together (I don't think there is a convenient/cheap way to demo them online anyways), but at least it will be out there for other people to experiment with..

**Comment by loganpowell** [comment]
So, I guess I'm going to have to use this in my project now. You've won me over.

**Comment by loganpowell** [comment]
For demo'ing React Native, I've seen this work:

https://snack.expo.io/

**Comment by pshrmn** [comment]
Minor update:

Currently, the "recommended" way to render a React app is like this, where `ReactDOM.render` is called every time a response is emitted.

```jsx
router.respond(response => {
  ReactDOM.render((
    <CuriBase router={router} response={response} render={render} />
  ), holder);
});
```

Based on my understanding, this approach will not work with React Native since you have to register a root component. Instead, we will need some sort of root component that will subscribe to the router and update its `state`.

```jsx
const App = () => (
  <ResponsiveBase router={router} render={render} />
);
AppRegistry.registerComponent('App', () => App);
```

I have a few ideas on how this would work (this is a general React thing, not React Native exclusive) and I am interested in getting some input.

1. **A `responsive` prop** Add a prop to the `CuriBase` that automatically subscribes this (makes it similar to a Redux `<Provider>`).

```jsx
const App = () => (
  <CuriBase router={router} render={render} responsive />
);
```

2. **Render function** A function that gets the `router`, subscribes to it, and calls the `render` function whenever a new response is emitted. This is more verbose, but could also be used with any component that you want to automatically update when a response is emitted.

```jsx
const App = () => (
  <Responsive router={router} render={(response) => (
    <CuriBase router={router} response={response} render={render} />
  )}/>
);
```

3. **Higher-order Component** Similar to the render function, but using an HoC.

```jsx
const ResponsiveBase = responsive(CuriBase);
const App = () => (
  <ResponsiveBase router={router} render={render} />
);
```

---

The other thing to think about is what to render _before_ the first response is emitted. The easiest way to handle this is by checking if a `response` exists in the `render` function and rendering some loading component when it is not. Unless the initial response makes a long data request, this loading component should basically be immediately replaced, so returning `null` isn't the worst thing to do here.

```jsx
function render(response) {
  if (response === null) {
    return <Loading /> // or return null ?
  }
  // ...
}
```

**Comment by loganpowell** [comment]
I can't really help you out here, but I do know some history of the evolution of React Router (and the reason they lost some of their steam as they changed their API from v3 to v4). They started out with a HOC (in v3) and moved to a [Render function](https://cdb.reacttraining.com/use-a-render-prop-50de598f11ce). 

However, they are - as you [stated so well in your article](https://medium.com/@pshrmn/i-have-to-learn-another-router-d2a770e72c92):

> React Router is a decentralized router. Its route matching is done using React’s render cycle, so for better or for worse it does depend on React. However, I’m focusing on centralized routers, which are more common, so we’re just going to ignore it.

Just a fleeting thought: what if - instead of coupling your router to the UI systems of these frameworks - you would couple your integrations with their state management systems (since yours is a 'centralized' system and - perhaps - therefore a source of truth)...

I'm sorry for bubbling up what might not only be a harmlessly stupid idea, but maybe also a warrantless distraction.

**Comment by loganpowell** [comment]
Perhaps some inspiration or more distraction: 

https://github.com/faceyspacey/redux-first-router/blob/master/docs/react-native.md

**Comment by loganpowell** [comment]
Have you heard of [React Navigation](https://reactnavigation.org/docs/guides/linking)?

**Comment by pshrmn** [comment]
Yes, the popularity of existing solutions like React Navigation combined with my lack of familiarity with RN dev is one of the reasons why I hadn't been working on a RN package before. I'd like to learn RN and I'll probably take a closer look, but for the time being I couldn't recommend Curi over React Navigation for anything but experiments.

As far as store tie-in goes, there are the `@curi/redux` and `@curi/mobx` packages that I think are dead simple to integrate with Curi. Using Curi with stores can be convenient (let them handle deep updates), but I don't think that it should be a requirement.

**Comment by loganpowell** [comment]
Groovy. I've used Redux in the past and really didn't like all the boilerplate, but loved the clarity it gave my projects. I'm poised to try the new Apollo Client ([apollo-link-state](https://github.com/apollographql/apollo-link-state)) on this next project. I look forward to giving it a go with Curi

**Comment by loganpowell** [comment]
This might make you feel better (or not):
https://github.com/react-navigation/react-navigation/issues/2031

**Comment by pshrmn** [comment]
I just skimmed it, but that is interesting. The scariest thing for me about RN is that animated transitions seem to be everywhere in mobile apps, so I'm not sure how many custom components need to be written to do this. That said, the router doesn't actually have to supply the transitions and I think that `match.response` can be used to set any transition data for a response, so it shouldn't be a big deal.

**Comment by pshrmn** [comment]
I was doing this [React Native Basics](https://learn.handlebarlabs.com/) (but with Curi instead of React Navigation) and have a couple of notes:

1. Setting up the back button handling is quite easy using the `BackHandler` and the router instance. I just closed the app when pressing the back button from the home screen.

```js
import { BackHandler } from 'react-native';

const router = curi(history, routes);

BackHandler.addEventListener("hardwareBackPress", () => {
  // close the app 
  if (router.history.index === 0) {
    return false;
  }
  router.history.go(-1);
  return true;
});
```

2. I used both the `<Curious>` component and `connect` (after integrating Redux and the router with `@curi/redux`) to make the `<CuriBase>` re-render when responses are emitted.

```jsx
// vanilla
import { CuriBase, Curious } from '@curi/react-native';

<Curious
  router={router}
  responsive={true}
  render={props => <CuriBase render={render} {...props} />}
/>

// redux
import { syncResponses, curiReducer } from '@curi/redux';

const reducer = combineReducers({ curi: curiReducer, ... });
const store = ...;
syncResponses(store, router);

const ResponsiveBase = connect(
  ({ curi }) => ({
    router: curi.router,
    response: curi.response,
    action: curi.action
  })
)(CuriBase);

<Provider store={store}>
  <ResponsiveBase render={render} />
</Provider>
```

**Comment by pshrmn** [comment]
@loganpowell I was looking a bit at other React Native navigation packages and I was wondering if you can confirm something. It seems like the "navigators" are just for 1) transitioning between screens and 2) providing base screen components (based on the navigator type) with common UI (e.g. headers). Does that sound right to you?

**Comment by loganpowell** [comment]
Good morning @pshrmn. I cannot answer that definitively as I don't know, but I did find a similar question and answer for React Nav: https://github.com/react-navigation/react-navigation/issues/289#issuecomment-279090028

**Comment by pshrmn** [comment]
I think that the [`@curi/react-native`](https://curi.js.org/packages/@curi/react-native/) package is in a good enough place right now to close this.

Implementation is mostly similar to a regular React app and the [React Native tips](https://curi.js.org/guides/react-native/) guide covers a few extra things to know.
