### ISSUE TITLE
Status on Redux Package

### ISSUE THREAD

**Issue by bfillmer** [pshrmn/curi#84]
Dug through the release notes and such, no mention, is the redux package discontinued moving forward?

**Comment by pshrmn** [comment]
When I originally implemented `@curi/redux`, the idea was to use Redux (and MobX because I made a package for that, too) to pass router/response data to components. The benefit of this was that it gave deep updates for "free", so I didn't have to setup some subscription system for people who use pure components/`shouldComponentUpdate`.

I removed the Redux package when React's new context was released because that is better suited for deep updates. Redux was no longer needed for passing the routing data and because of how the new context API's provider/consumer pairs work, there wasn't even a great way for "Curi aware" components to get their data from Redux instead.

While I generally think that linking Curi and Redux is not necessary, I'm not completely against bringing a Redux package back, but I would have to have a better understanding of the use cases. If you just want the responses to be in the store, that is easy enough, but if you wanted to use Redux as the sole source for passing response data throughout an application, then things might get a bit tricky.

**Comment by bfillmer** [comment]
Understood. I generally use Redux, for now anyway, as the single source of truth for both my component layer and my saga layer to know what to render/run. An example of my usage: https://github.com/bfillmer/greenfield/

Ultimately I have no reason not to just roll my own equivalent of `syncResponses`, I was about halfway through doing that myself originally when I found the Redux package for Curi.

**Comment by pshrmn** [comment]
If you run into any issues with that, please let me know.
