### ISSUE TITLE
Website is broken?

### ISSUE THREAD

**Issue by dbismut** [pshrmn/curi#90]
Title sums it up.
Tested on Chrome and Safari.

Console returns:

> ReferenceError: Can't find variable: IntersectionObserver

**Comment by pshrmn** [comment]
Hmm, I'm not seeing any issues in Chrome locally. What version are you using? This [MDN table](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API#Browser_compatibility) shows Chrome support for `IntersectionObserver` at v51.

It looks like Safari doesn't support the `IntersectionObserver` yet, but I believe that the check for `IntersectionObserver` should be sufficient.

Could you please try this in the console of Chrome and Safari and reporting the results?

```js
if (typeof window !== "undefined" && IntersectionObserver) {
  console.log("IntersectionObserver exists");
} else {
  console.log("IntersectionObserver DOES NOT exist");
}
```
The solution might be to reference `IntersectionObserver` as `window.IntersectionObserver`, but TypeScript doesn't like that, so I'll have to do some digging to find the ideal workaround if that is required.

**Comment by dbismut** [comment]
Sorry, I've done a bad job reporting. I swear I had tested on Desktop Chrome but it actually works on Desktop Chrome, fails on Safari Desktop, Safari Mobile and Chrome Mobile iOS. I'm not sure I can help, but isn't there a polypill for `IntersectionObserver`?

**Comment by pshrmn** [comment]
Okay, so if my understanding of iOS is correct, every browser there is using WebKit (or whatever it is that iOS provides, not their native engines), which is why Chrome on iOS is having issues.

I believe you are right that I can polyfill `IntersectionObserver`, but can you also run that `if/else` statement in the console? I don't have any Apple devices, so I can't test it myself, but I am curious if that is insufficient for verifying `InteresctionObserver` exists. Polyfills are great for patching behavior, but I also don't want sites to break if no polyfill is provided.

**Comment by dbismut** [comment]
Hey sure. I've run the code you ask with a slight modification so that it does what you intended:
```js
if (typeof window !== "undefined" && window.IntersectionObserver) {
  console.log("IntersectionObserver exists");
} else {
  console.log("IntersectionObserver DOES NOT exist");
}
```

So:

| Browser                    | Platorm | Version        | Console         | Website |
|---------------------------|-----|-----------|-------------------------------------|------------------------|
| **Safari Technology Preview** | **Mac** | 12.1    | `IntersectionObserver DOES NOT exist` | Blank page             |
| **Chrome**                    | **Mac** | 69        | `IntersectionObserver exists`         | Website shows normally |
| **Safari**                    | **iOS beta** | 12 | `IntersectionObserver DOES NOT exist` | Blank page             |
| **Chrome**                    | **iOS** | 68        | NA                                  | Blank page             |

**Comment by pshrmn** [comment]
Thanks for the research. The `window.IntersectionObserver` check is definitely what I want, now I just have to figure out how to add that and make TypeScript happy.

**Comment by pshrmn** [comment]
@dbismut if you wouldn't mind double checking everything, I added a polyfill for `IntersectionObserver`, so hopefully Safari/iOS works as expected now. I'll roll out a fix for `<Prefetch>` (the component that uses `IntersectionObserver`) soon, too, so that everything doesn't break in the absence of a polyfill.

**Comment by dbismut** [comment]
@pshrmn all good ;)
